import Head from 'next/head'

export function mainLayout(page: any) {
    return (
        <>
            <Head>
                <title>Japanese rice recipe</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <header></header>

            <main>
                {page}
            </main>

            <footer></footer>
        </>
    )
}